apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ (include "zerossl_cert_manager.fullname" .) }}-clusterrole
  labels:
    {{- include "zerossl_cert_manager.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: zerossl-cert-manager
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]