{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  namespace: {{ include "zerossl_cert_manager.namespace" . }}
  name: {{ .Values.priorityClass.name }}
  labels:
    {{- include "zerossl_cert_manager.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: zerossl-cert-manager
value: {{ .Values.priorityClass.value }}
globalDefault: false
description: "Priority class for zerossl issuer"
{{- end }}
