{{ if eq .Values.type "cronjob" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ (include "zerossl_cert_manager.fullname" .) }}-role-binding
  namespace: {{ include "zerossl_cert_manager.namespace" . }}
  labels:
    {{- include "zerossl_cert_manager.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: zerossl-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ (include "zerossl_cert_manager.fullname" .) }}-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ include "zerossl_cert_manager.namespace" . }}
{{- end -}}